# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    assignees:
      - "z0n"
    reviewers:
      - "z0n"
    groups:
      ci:
        patterns:
          - "husky"
          - "lint-staged"
          - "vercel"
      css:
        patterns:
          - "autoprefixer"
          - "clsx"
          - "postcss"
          - "tailwindcss"
      eslint:
        patterns:
          - "*eslint*"
          - "prettier"
          - "prettier-plugin-tailwindcss"
      nextjs:
        patterns:
          - "@next/bundle-analyzer"
          - "eslint-config-next"
          - "next"
      react:
        patterns:
          - "@types/react"
          - "@types/react-dom"
          - "react"
          - "react-dom"
      storybook:
        patterns:
          - "*storybook*"
      testing:
        patterns:
          - "@vitejs/plugin-react"
          - "jsdom"
          - "msw"
          - "*testing-library*"
          - "vite-tsconfig-paths"
          - "vitest"
      typescript:
        patterns:
          - "@types/node"
          - "typescript"
          - "tsconfig-paths-webpack-plugin"
